CREATE DATABASE customer_behaviour;
use customer_behaviour;
show tables;
select * from customer_shopping limit 10;
show tables;
select * from customer_shopping_cleaned;
# What is the total revenue generated by male vs female customer
SELECT gender, SUM(purchase_amount) AS Revenue
FROM customer_shopping
GROUP BY gender;
# Which customers a used a discount but still spent more than the average purchase amount
SELECT * FROM customer_shopping;
select customer_id, purchase_amount
FROM customer_shopping
where discount_applied  = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_shopping);

# which are the top 5 products with highest average review rating
SELECT item_purchased, AVG(review_rating) AS average_product_rating
FROM customer_shopping 
GROUP BY item_purchased
order by avg(review_rating) desc
limit 5;
# Compare the average purchase amounts between standarad and Express Shipping
SELECT * FROM customer_shopping;
SELECT shipping_type, AVG(purchase_amount) 
FROM customer_shopping
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type;
# Do subscribe customers spend more?  Compare avearage spend and total revenue between subscribers and non-subscribers
SELECT * FROM customer_shopping;
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS Revenue
FROM customer_shopping
GROUP BY subscription_status
ORDER BY Revenue, avg_spend DESC;
SELECT * FROM CUSTOMER_SHOPPING;
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# Segement customers in new, Returning, and loyal based on their total number of previous purchases, and show the count of each segement

WITH customer_type AS
(
 SELECT customer_id, previous_purchases,
 CASE WHEN previous_purchases=1 THEN 'NEW'
	  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'loyal'
      END AS 'customer_segment'
FROM Customer_Shopping

)

SELECT customer_segment, count(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

# What are the top 3 most purchased product in each cagtegory
SELECT * FROM CUSTOMER_SHOPPING;

WITH item_counts AS
(
 SELECT category,
		item_purchased,
        count(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
        FROM customer_shopping 
        GROUP BY category, item_purchased

)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

# Are customers who are repeat customers more than 5 previous purchases also likely to subscribe
SELECT subscription_status,
count(customer_id) AS repeat_buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;

# What is the revenue contribution of each age group
SELECT age_group,
SUM(purchase_amount) AS Revenue
FROM customer_shopping
GROUP BY age_group
ORDER BY Revenue DESC;
